- name: Install puppetserver dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openjdk-8-jre-headless
- name: Install puppetserver
  apt:
    name: puppetserver
    state: present
